config:
  example:
    org: org0
    lib: miracl
    auths:
      - "auth0"
      - "auth1"
    user: marcello.paris@gmail.com
    attrs:
      - "A@auth0"
      - "B@auth0"
      - "E=5@auth1"
    policy: "(E@auth1 == 4) /\\ B@auth0"
  arithmetic:
    library: miracl
    curve: BN254
    seed: abcdef
  storage:
    redis:
      local0:
        addr: 127.0.0.1:6379
        password:
    leveldb:
      local0:
        name: mosaic.db
  active:
    type: leveldb
    label: local0
